api/urls.py
from django.urls import path
from api import views

urlpatterns = [
    path('login/', views.LoginView.as_view()),
    path('message/', views.MessageView.as_view()),
]

bom/urls.py
from django.urls import path
from . import views
from . import bominfo_to_bomlist_views

app_name = 'bom'

urlpatterns = [
    path('test02/', views.test02),
    path('test/<int:id>/', views.test,name='test'),
    path('test_reverse/<int:id>/', views.test_reverse,name='test_reverse'),
    #path('index/<int:id>/', views.index,name='index'),
    path('', views.index,name='index'),
    path('supplierlist/',views.SupplierListView.as_view(),name='supplierlist'),
    path('supplier/',views.supplier,name='supplier'),
    path('supplier_add/',views.supplier_add,name='supplier_add'),
    path('supplier_edit/<str:code>/',views.supplier_edit,name='supplier_edit'),
    path('supplier_del/<str:code>/',views.supplier_del,name='supplier_del'),
    path('supplier_handle/',views.supplier_handle,name='supplier_handle'),
    path('categorylist/',views.CategoryListView.as_view(),name='categorylist'),
    path('category/',views.category,name='category'),
    path('category_add/',views.category_add,name='category_add'),
    path('category_del/<str:code>/', views.category_del, name='category_del'),
    path('category_edit/<str:code>/',views.category_edit,name='category_edit'),
    path('category_handle/',views.category_handle,name='category_handle'),
    path('projectlist/',views.ProjectListView.as_view(),name='projectlist'),
    path('project/',views.project,name='project'),
    path('project_add/',views.project_add,name='project_add'),
    path('project_edit/<int:id>/',views.project_edit,name='project_edit'),
    path('project_del/<int:id>/',views.project_del,name='project_del'),
    path('project_handle',views.project_handle,name='project_handle'),
    path('materiallist/',views.MaterialtListView.as_view(),name='materiallist'),
    path('material/',views.material,name='material'),
    path('material_add/', views.material_add, name='material_add'),
    path('material_edit/<str:code>/', views.material_edit, name='material_edit'),
    path('material_del/<str:code>/', views.material_del, name='material_del'),
    path('material_handle', views.material_handle, name='material_handle'),
    path('bominfolist/',views.BominfoListView.as_view(),name='bominfolist'),
    path('bominfo/',views.bominfo,name='bominfo'),
    path('bomlistlist/',views.BomlistListView.as_view(),name='bomlistlist'),
    path('ecnlist/',views.EcnListView.as_view(),name='ecnlist'),
    path('ecn/',views.ecn,name='ecn'),
    path('ecn_add/',views.ecn_add,name='ecn_add'),
    path('ecn_edit/<int:id>/', views.ecn_edit, name='ecn_edit'),
    path('ecn_del/<int:id>/', views.ecn_del, name='ecn_del'),
    path('ecn_handle/', views.ecn_handle, name='ecn_handle'),
    path('bominfotobomlistlist/', views.BominfoToBomlistListView.as_view(),name='bominfotobomlistlist'),
    path('bomdetail/<str:bomname>/', views.bomdetail,name='bomdetail'),
    path('specific_bom_detail/<str:bomname>/', bominfo_to_bomlist_views.specific_bom_detail,name='specific_bom_detail'),

]

djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('api/',include('api.urls')),
    path('bom/',include('bom.urls')),
    path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls),
]

bom/models.py
from django.db import models

#供应商表
class Supplier(models.Model):
    #供应商编码
    code = models.CharField(max_length=10,primary_key=True,verbose_name='供应商编码')
    #供应商名称
    name = models.CharField(max_length=50,db_index=True,verbose_name='供应商名称')
    #联系人姓名
    contacts_name = models.CharField(max_length=50,blank=True,null=True,verbose_name='联系人')
    # 联系人电话
    contacts_phone = models.CharField(max_length=20,blank=True,null=True,verbose_name='电话')
    # 联系人职位
    contacts_position = models.CharField(max_length=20,blank=True,null=True,verbose_name='职位')
    # 联系地址
    address = models.CharField(max_length=100,blank=True,null=True,verbose_name='地址')
    #是否有效
    isvalid_choices = [
        (0, '无效'),
        (1, '有效'),
    ]
    isvalid = models.IntegerField(choices=isvalid_choices,default=1)

    def __str__(self):
        return self.name

#物料类别表
class Category(models.Model):
    #物料类别码
    code = models.CharField(max_length=4, primary_key=True)
    #类别名称
    name = models.CharField(max_length=20,null=True)
    #是否有效
    isvalid_choices = [
        (0, '无效'),
        (1, '有效'),
    ]
    isvalid = models.IntegerField(choices=isvalid_choices,default=1)

    def __str__(self):
        return self.name

class Material(models.Model):
    #物料编码
    code = models.CharField(max_length=9, primary_key=True,verbose_name='物料编码')
    #物料描述
    description = models.CharField(max_length=100,default='',verbose_name='物料描述')
    #物料型号
    partnumber = models.CharField(max_length=50,default='',db_index=True,verbose_name='物料型号')

    isvalid_choices = [
        (0, '无效'),
        (1, '有效'),
    ]
    isvalid = models.IntegerField(choices=isvalid_choices,default=1,null=True)

    #物料标记
    flag = models.CharField(max_length=10,blank=True,null=True)
    #供应商
    supplier = models.ForeignKey(Supplier,on_delete=models.CASCADE,verbose_name='供应商',null=True)
    #所属类别
    category = models.ForeignKey(Category,on_delete=models.CASCADE,verbose_name='类别',null=True)

    def __str__(self):
        return str(self.code)
        #return f'{self.code} {self.description} {self.partnumber} {self.supplier}'

class Project(models.Model):
    #项目名称
    name = models.CharField(max_length=20,unique=True)
    #项目配置描述
    description = models.CharField(max_length=100,default='')

    def __str__(self):
        return self.name

#bom信息
class Bominfo(models.Model):
    #BOM列表的名称，存放BOM表的文件名称
    bomname = models.CharField(max_length=30,unique=True)
    #硬件版本号
    hw_version = models.CharField(max_length=5,null=True)
    #BOM配置描述
    description = models.CharField(max_length=100,default='')
    #该Bom文件隶属于某个项目
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    #多对多器件列表 Material
    material = models.ManyToManyField(
        Material,
        through='bomlist',
        through_fields=('bominfo','material'),
    )
    def __str__(self):
        return self.bomname

class Bomlist(models.Model):
    #此条信息（包含物料、用量、位号等）所关联的bom名称
    bominfo = models.ForeignKey(Bominfo,on_delete=models.CASCADE)
    #器件列表
    material = models.ForeignKey(Material,on_delete=models.CASCADE)
    #用量
    num = models.IntegerField(max_length=5,default=1)
    #位号序列
    references = models.CharField(max_length=1000,default='')
    def __str__(self):
        return f'{self.bominfo}---{self.material}'

#ECN表
class Ecn(models.Model):
    #变更内容描述
    content = models.CharField(max_length=200)
    #状态
    state_choices = [
        (0, '未执行'),
        (1, '已执行'),
    ]
    state = models.IntegerField(choices=state_choices,default=0)
    #变更原因
    reason = models.CharField(max_length=100,null=True)
    #创建时间
    createtime = models.DateTimeField()
    #执行方式
    action_choices = [
        (0, '立即执行'),
        (1, '消化现有库存后执行'),
    ]
    action = models.IntegerField(choices=action_choices,default=0)
    #发起人
    createdby = models.CharField(max_length=20)
    #related bom
    bominfo = models.ForeignKey(Bominfo,on_delete=models.CASCADE)

bom/views.py
from django.core.paginator import Paginator

from django.urls import reverse
from django.views.generic import View
from django.views.generic.list import ListView
from django.shortcuts import render
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect
from .models  import *
from django.http import JsonResponse
from django.db.models import F


# 用Listview实现Supplier列表显示
class SupplierListView(ListView):
    #查询的模型
    model = Supplier
    #每页显示5条
    paginate_by = 5

# 用Listview实现Supplier列表显示
class CategoryListView(ListView):
    #查询的模型
    model = Category
    #每页显示5条
    paginate_by = 5

# 用Listview实现Project列表显示
class ProjectListView(ListView):
    #查询的模型
    model = Project
    #每页显示5条
    paginate_by = 5

# 用Listview实现Material列表显示
class MaterialtListView(ListView):
    #查询的模型
    model = Material
    #每页显示5条
    paginate_by = 10

# 用Listview实现Bominfo列表显示
class BominfoListView(ListView):
    #查询的模型
    model = Bominfo
    #每页显示5条
    paginate_by = 10

# 用Listview实现Bomlist列表显示
class BomlistListView(ListView):
    #查询的模型
    model = Bomlist
    #每页显示5条
    paginate_by = 10

# 从Bominfo查询bomlist明细
class BominfoToBomlistListView(ListView):
    #查询的模型
    #model = Bomlist
    template_name = 'bom/bominfotobomlist_list.html'
    def get_queryset(self):
        #qs = super().get_queryset()  # 调用父类方法
        bomname = self.request.GET.get('bomname',None)
        qs = Bomlist.objects.values('material__code','material__description','material__partnumber','material__supplier__name','num','references').filter(bominfo__bomname=bomname)
        return qs
    def get_context_data(self, **kwargs):
        bomname = self.request.GET.get('bomname')
        bominfo = Bominfo.objects.filter(bomname=bomname)
        context = super().get_context_data(**kwargs)
        context.update({'bomname': bomname,'hw_version':bominfo.first().hw_version,'description':bominfo.first().description,'project':bominfo.first().project})
        return context
    paginate_by = 500

# 用Listview实现# 用Listview实现Ecn列表显示列表显示
class EcnListView(ListView):
    #查询的模型
    model = Ecn
    paginate_by = 10

#首页
def index(request):
    project = Project.objects.all()
    supplier = Supplier.objects.all()
    category = Category.objects.all()
    return render(request,'index.html',locals())

def project(request):
    project = Project.objects.all()
    paginator = Paginator(project, 10)  # 根据指定的每页列表大小进行分页
    try:
        current_page_num = int(request.GET.get('page', 1))  # 根据url获取当前页，没有时取1
        project = paginator.page(current_page_num)  # 根据页数获取特定页的列表
        page_num = paginator.num_pages
        page_range = paginator.page_range
    except EmptyPage:
        project = paginator.page(1)
    return render(request,'page_project.html',locals())

#添加项目信息
def project_add(request):
    return render(request,'page_project_add.html',locals())
#项目信息编辑
def project_edit(request,id):
    project = Project.objects.get(id=id)
    return render(request,'page_project_edit.html',locals())
#处理项目信息编辑表单
def project_handle(request):
    if request.POST:
        if 'add' in request.POST:
            name = request.POST.get('name')
            description = request.POST.get('description')
            Project.objects.update_or_create(name=name,description=description)
        if 'modify' in request.POST:
            id = request.POST.get('id')
            name = request.POST.get('name')
            description = request.POST.get('description')
            Project.objects.filter(id=id).update(name=name,description=description)
        if 'del' in request.POST:
            id = request.POST.get('id')
            Project.objects.filter(id=id).delete()

        return HttpResponseRedirect(reverse('bom:project'))
    else:
        return HttpResponse('POST提交错误')

#删除项目信息
def project_del(request,id):
    try:
        Project.objects.filter(id=id).delete()
        return HttpResponseRedirect(reverse('bom:project'))
    except Exception as e:
        return HttpResponse('删除数据错误')

def category(request):
    # project = Project.objects.all()
    # supplier = Supplier.objects.all()
    category = Category.objects.all().order_by('code')
    paginator = Paginator(category, 10)  # 根据指定的每页列表大小进行分页
    try:
        current_page_num = int(request.GET.get('page', 1))  # 根据url获取当前页，没有时取1
        category = paginator.page(current_page_num)  # 根据页数获取特定页的列表
        page_num = paginator.num_pages
        page_range = paginator.page_range
    except EmptyPage:
        category = paginator.page(1)
    return render(request,'page_category.html',locals())

#添加分类
def category_add(request):
    return render(request,'page_category_add.html',locals())
#分类信息编辑
def category_edit(request,code):
    category = Category.objects.get(code=code)
    return render(request,'page_category_edit.html',locals())
#处理分类信息编辑表单
def category_handle(request):
    if request.POST:
        if 'add' in request.POST:
            code = request.POST.get('code')
            name = request.POST.get('name')
            isvalid = request.POST.get('isvalid')
            print(code,name,isvalid)
            Category.objects.update_or_create(code=code, name=name, isvalid=isvalid)
        if 'modify' in request.POST:
            code = request.POST.get('code')
            name = request.POST.get('name')
            isvalid = request.POST.get('isvalid')
            Category.objects.filter(code=code).update(name=name, isvalid=isvalid)
        if 'del' in request.POST:
            code = request.POST.get('code')
            Category.objects.filter(code=code).delete()
        return HttpResponseRedirect(reverse('bom:category'))
    else:
        return HttpResponse('POST提交错误')

#删除分类
def category_del(request,code):
    try:
        Category.objects.filter(code=code).delete()
        return HttpResponseRedirect(reverse('bom:category'))
    except Exception as e:
        return HttpResponse('删除数据错误')

def supplier(request):
    # project = Project.objects.all()
    supplier = Supplier.objects.all()
    paginator = Paginator(supplier, 10)  # 根据指定的每页列表大小进行分页
    try:
        current_page_num = int(request.GET.get('page', 1))  # 根据url获取当前页，没有时取1
        supplier = paginator.page(current_page_num)  # 根据页数获取特定页的列表
        page_num = paginator.num_pages
        page_range = paginator.page_range
    except EmptyPage:
        supplier = paginator.page(1)
    return render(request,'page_supplier.html',locals())

#添加供应商信息
def supplier_add(request):
    return render(request,'page_supplier_add.html',locals())
#供应商信息编辑
def supplier_edit(request,code):
    supplier = Supplier.objects.get(code=code)
    return render(request,'page_supplier_edit.html',locals())
#处理供应商信息编辑表单
def supplier_handle(request):
    if request.POST:
        if 'add' in request.POST:
            code = request.POST.get('code')
            name = request.POST.get('name')
            contacts_name = request.POST.get('contacts_name')
            contacts_phone = request.POST.get('contacts_phone')
            contacts_position = request.POST.get('contacts_position')
            address = request.POST.get('address')
            isvalid = request.POST.get('isvalid')
            # print(code,name,isvalid)
            Supplier.objects.update_or_create(code=code, name=name, contacts_name=contacts_name, contacts_phone=contacts_phone, contacts_position=contacts_position, address=address, isvalid=isvalid)
        if 'modify' in request.POST:
            code = request.POST.get('code')
            name = request.POST.get('name')
            contacts_name = request.POST.get('contacts_name')
            contacts_phone = request.POST.get('contacts_phone')
            contacts_position = request.POST.get('contacts_position')
            address = request.POST.get('address')
            isvalid = request.POST.get('isvalid')
            # print(code,name,isvalid)
            Supplier.objects.filter(code=code).update(name=name, contacts_name=contacts_name, contacts_phone=contacts_phone, contacts_position=contacts_position, address=address)
        if 'del' in request.POST:
            code = request.POST.get('code')
            Supplier.objects.filter(code=code).delete()

        return HttpResponseRedirect(reverse('bom:supplier'))
    else:
        return HttpResponse('POST提交错误')
#删除供应商
def supplier_del(request,code):
    try:
        Supplier.objects.filter(code=code).delete()
        return HttpResponseRedirect(reverse('bom:supplier'))
    except Exception as e:
        return HttpResponse('删除数据错误')

def material(request):
    material = Material.objects.all()
    paginator = Paginator(material, 10)  # 根据指定的每页列表大小进行分页
    try:
        current_page_num = int(request.GET.get('page', 1))  # 根据url获取当前页，没有时取1
        material = paginator.page(current_page_num)  # 根据页数获取特定页的列表
        page_num = paginator.num_pages
        page_range = paginator.page_range
    except EmptyPage:
        material = paginator.page(1)
    return render(request,'page_material.html',locals())

#添加供应商信息
def material_add(request):
    return render(request,'page_material_add.html',locals())
#供应商信息编辑
def material_edit(request,code):
    material = Material.objects.get(code=code)
    return render(request,'page_material_edit.html',locals())
#处理供应商信息编辑表单
def material_handle(request):
    if request.POST:
        if 'add' in request.POST:
            code = request.POST.get('code')
            description = request.POST.get('description')
            partnumber = request.POST.get('partnumber')
            isvalid = request.POST.get('isvalid')
            flag = request.POST.get('flag')
            supplier = request.POST.get('supplier')
            category = request.POST.get('category')
            # print(code,name,isvalid)
            Material.objects.update_or_create(code=code, description=description, partnumber=partnumber, isvalid=isvalid, flag=flag)
        if 'modify' in request.POST:

bom/templates/index.html
{% extends 'base.html' %}
<!-- page content Start -->
{% block content %}
    <div class="content-page">
{#        <div class="container-fluid">#}
{#            <div class="card border-none">#}
{#                <div class="card-body custom-card-space">#}
                    <div class="row">
                        <div class="col-lg-3">
                            <div class="card">
                                <div class="card-body">
                                    <div class="d-flex align-items-top justify-content-between mb-4">
                                        <a href="{% url 'bom:bominfo' %}">
                                            <svg height="130" width="500">
                                                <defs>
                                                <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="0%">
                                                  <stop offset="0%" style="stop-color:rgb(255,255,0);stop-opacity:1" />
                                                  <stop offset="100%" style="stop-color:rgb(255,30,0);stop-opacity:1" />
                                                </linearGradient>
                                                </defs>

                                                <ellipse cx="80" cy="60" rx="80" ry="45" fill="url(#grad1)" />

                                                <text fill="#ffffff" font-size="20" font-family="Verdana" x="20" y="70">BOM信息汇总</text>
                                            </svg>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="card">
                                <div class="card-body">
                                    <div class="d-flex align-items-top justify-content-between mb-4">
                                            <a href="{% url 'bom:ecn' %}">
                                                <svg height="130" width="500">
                                                    <defs>
                                                    <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="0%">
                                                      <stop offset="0%" style="stop-color:rgb(255,255,0);stop-opacity:1" />
                                                      <stop offset="100%" style="stop-color:rgb(255,30,0);stop-opacity:1" />
                                                    </linearGradient>
                                                    </defs>

                                                    <ellipse cx="80" cy="60" rx="80" ry="45" fill="url(#grad1)" />

                                                    <text fill="#ffffff" font-size="45" font-family="Verdana" x="35" y="76">ECN</text>
                                                </svg>
                                            </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="card">
                                <div class="card-body">
                                    <div class="d-flex align-items-top justify-content-between mb-4">
                                            <a href="{% url 'bom:material' %}">
                                                <svg height="130" width="500">
                                                    <defs>
                                                    <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="0%">
                                                      <stop offset="0%" style="stop-color:rgb(255,255,0);stop-opacity:1" />
                                                      <stop offset="100%" style="stop-color:rgb(255,30,0);stop-opacity:1" />
                                                    </linearGradient>
                                                    </defs>

                                                    <ellipse cx="80" cy="60" rx="80" ry="45" fill="url(#grad1)" />

                                                    <text fill="#ffffff" font-size="30" font-family="Verdana" x="20" y="70">物料管理</text>
                                                </svg>
                                            </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="card">
                                <div class="card-body">
                                    <div class="d-flex align-items-top justify-content-between mb-4">
                                            <a href="{% url 'bom:supplier' %}">
                                                <svg height="130" width="500">
                                                    <defs>
                                                    <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="0%">
                                                      <stop offset="0%" style="stop-color:rgb(255,255,0);stop-opacity:1" />
                                                      <stop offset="100%" style="stop-color:rgb(255,30,0);stop-opacity:1" />
                                                    </linearGradient>
                                                    </defs>

                                                    <ellipse cx="80" cy="60" rx="80" ry="45" fill="url(#grad1)" />

                                                    <text fill="#ffffff" font-size="25" font-family="Verdana" x="20" y="70">供应商管理</text>
                                                </svg>
                                            </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="card">
                                <div class="card-body">
                                    <div class="d-flex align-items-top justify-content-between mb-4">
                                            <a href="{% url 'bom:category' %}">
                                                <svg height="130" width="500">
                                                    <defs>
                                                    <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="0%">
                                                      <stop offset="0%" style="stop-color:rgb(255,255,0);stop-opacity:1" />
                                                      <stop offset="100%" style="stop-color:rgb(255,30,0);stop-opacity:1" />
                                                    </linearGradient>
                                                    </defs>

                                                    <ellipse cx="80" cy="60" rx="80" ry="45" fill="url(#grad1)" />

                                                    <text fill="#ffffff" font-size="20" font-family="Verdana" x="20" y="70">物料类别管理</text>
                                                </svg>
                                            </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="card">
                                <div class="card-body">
                                    <div class="d-flex align-items-top justify-content-between mb-4">
                                            <a href="{% url 'bom:project' %}">
                                                <svg height="130" width="500">
                                                    <defs>
                                                    <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="0%">
                                                      <stop offset="0%" style="stop-color:rgb(255,255,0);stop-opacity:1" />
                                                      <stop offset="100%" style="stop-color:rgb(255,30,0);stop-opacity:1" />
                                                    </linearGradient>
                                                    </defs>

                                                    <ellipse cx="80" cy="60" rx="80" ry="45" fill="url(#grad1)" />

                                                    <text fill="#ffffff" font-size="25" font-family="Verdana" x="28" y="70">项目管理</text>
                                                </svg>
                                            </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
{#                </div>#}
{#            </div>#}
{#	    </div>#}
    </div>
{% endblock content %}
<!-- page content end  -->

bom/templates/page_ecn_add.html
{% extends 'base.html' %}
<!-- page content Start -->
{% block content %}
	<div class="content-page">
       <div class="d-flex align-items-center justify-content-between mb-3">
           <h5>新增ECN</h5>
           <a href="{% url 'bom:ecn' %}" ><span style="float:right;"><h5>返回</h5></span></a>
       </div>
        <div>
            <form method="post" action="{% url 'bom:ecn_add' %}">
                {% csrf_token %}
                <label>变更内容：</label><textarea style="width: 300px;height: 100px" name="content"></textarea><br>
                <label>执行状态：</label><input style="width: 300px" name="state"><br>
                <label>变更原因：</label><input style="width: 300px" name="reason"><br>
                <label>创建时间：</label><input style="width: 300px" name="createtime"><br>
                <label>执行方式：</label><input style="width: 300px" name="action"><br>
                <label>发起人：</label><input style="width: 300px" name="createdby"><br><br>
                <label>关联BOM：</label><input style="width: 300px" name="bominfo"><br><br>

                <input type="submit" style="width: 120px" name="add" value="保  存">
            </form>
        </div>
    </div>
{% endblock content %}
<!-- page content end  -->

bom/templates/page_project.html
{% extends 'base.html' %}
<!-- page content Start -->
{% block content %}
	<div class="content-page">
       <div class="d-flex align-items-center justify-content-between mb-3">
           <h5>项目列表</h5>
           <a href="{% url 'bom:project_add' %}" ><span style="float:left;"><h5>添加</h5></span></a>
           <a href="" ><span style="float:left;"><h5>导入</h5></span></a>
           <a href="" ><span style="float:left;"><h5>导出</h5></span></a>
           <a href="{% url 'bom:index' %}" ><span style="float:right;"><h5>返回</h5></span></a>
       </div>
          <table width="100%" border="1" cellspacing="1" cellpadding="0">
             <thead class="text-uppercase">
                   <tr class="ligth ligth-data" align="center">
                      <th>No.</th>
                      <th>项目名称</th>
                      <th>项目描述</th>
                      <th>操作</th>
                   </tr>
             </thead>
             <tbody class="ligth-body">
             {% for proj in project %}
                 <tr>
                       <td>{{ proj.id }}</td>
                       <td>{{ proj.name }}</td>
                       <td>{{ proj.description }}</td>
                       <td>
                          <div align="center">
                                <a href="{% url 'bom:project_edit' proj.id %}">编辑</a>
                                <a href="{% url 'bom:project_del' proj.id %}">删除</a>
                          </div>
                       </td>
                 </tr>
             {% endfor %}
         {#分页展示#}
                <tr>
                    <td colspan="4">
                        {#首页#}
                        <a href="?page=1" aria-label="Next"><span aria-hidden="true">首页</span></a>
                        {#has_previous 判断是否有上一页#}
                        {% if project.has_previous %}
                            {#previous_page_number 上一页的页码#}
                            <a href="?page={{ project.previous_page_number }}" aria-label="Previous"><span
                                    aria-hidden="true">上一页</span></a>
                        {% else %}
                            {#class="disabled" 禁止用户点击#}
                            <a href="" aria-label="Previous"><span aria-hidden="true">上一页</span></a>
                        {% endif %}
                        {#遍历页码的列表#}
                        {% for i in page_range %}
                            {#判断当前页码数等于底部页码时#}
                            {% if current_page_num == i %}
                                {#增加class,加深按钮#}
                                <a href="?page={{ i }}">{{ i }}</a>
                            {% else %}
                                {#href参数为简写,它会自动获取当前路径，并拼接参数#}
                                <a href="?page={{ i }}">{{ i }}</a>
                            {% endif %}
                        {% endfor %}
                        {#has_next 判断是否有下一页#}
                        {% if project.has_next %}
                            {#next_page_number 下一页的页码#}
                            <a href="?page={{ project.next_page_number }}" aria-label="Next"><span
                                    aria-hidden="true">下一页</span></a>
                        {% else %}
                            {#class="disabled" 禁止用户点击#}
                            <a href="" aria-label="Next"><span aria-hidden="true">下一页</span></a>
                        {% endif %}
                        <a href="?page={{ paginator.num_pages }}" aria-label="Next"><span aria-hidden="true">最后一页</span></a>
                        <span style="float: right">第{{ current_page_num }}/{{ paginator.num_pages }}页</span>
                        <span style="float: right">共{{ paginator.count }}条记录，</span>
                    </td>
                </tr>
             </tbody>
          </table>
    </div>
{% endblock content %}
<!-- page content end  -->

bom/templates/test_reverse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>测试重定向</title>
</head>
<body>
    <a href="{% url 'bom:test' 7798768 %}"><h2>测试重定向</h2></a>
</body>
</html>